version: 0.2

env:
  variables:
    SRC_DIR: src/github.com/o3labs/transaction-log

phases:
  install:
     commands:
      - go get -u github.com/golang/dep/cmd/dep
      - type dep && dep version
  pre_build:
    commands:
      - mkdir -p ${GOPATH}/${SRC_DIR} && cd ${GOPATH}/${SRC_DIR}
      - mv ${CODEBUILD_SRC_DIR}/* ${CODEBUILD_SRC_DIR}/.??* .
      - dep ensure
  build:
    commands:
      - go build -o bin/transaction-log/transaction-log main.go
      - go build -o bin/transaction-log/transaction-log-consumer  consumer/main.go
      - cp config*.json bin/transaction-log/
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - bin/**/*
    - scripts/**
