version: 0.2

env:
  variables:
    SRC_DIR: /go/src/github.com/o3labs/transaction-log

phases:
  install:
     commands:
      - chmod +x /go/bin/dep
  pre_build:
    commands:
      - mkdir -p ${SRC_DIR}
      - echo ${CODEBUILD_SRC_DIR}
      - echo ${SRC_DIR}
      - mv ${CODEBUILD_SRC_DIR}/* ${SRC_DIR}/
      - cd ${SRC_DIR}
      - /go/bin/./dep ensure
  build:
    commands:
      - go build -o bin/transaction-log/transaction-log main.go
      - go build -o bin/transaction-log/transaction-log-consumer  consumer/main.go
      - cp config*.json bin/transaction-log/
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - ${SRC_DIR}/bin/**/*
    - ${SRC_DIR}/scripts/**
    - appspec.yml
