version: 0.2

env:
  variables:
    SRC_DIR: src/github.com/o3labs/transaction-log

phases:
  install:
     commands:
      - chmod +x /go/bin/dep
  pre_build:
    commands:
      - /go/bin/./dep ensure
  build:
    commands:
      - go build -o bin/transaction-log/transaction-log main.go
      - go build -o bin/transaction-log/transaction-log-consumer  consumer/main.go
      - cp config*.json bin/transaction-log/
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - bin/**/*
    - scripts/**
